// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class DispatchDocumentsArgsParameterDocumentsItem
    {
        /// <summary>
        /// Initializes a new instance of the
        /// DispatchDocumentsArgsParameterDocumentsItem class.
        /// </summary>
        public DispatchDocumentsArgsParameterDocumentsItem() { }

        /// <summary>
        /// Initializes a new instance of the
        /// DispatchDocumentsArgsParameterDocumentsItem class.
        /// </summary>
        public DispatchDocumentsArgsParameterDocumentsItem(int? recno = default(int?), string documentNumber = default(string))
        {
            Recno = recno;
            DocumentNumber = documentNumber;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Recno")]
        public int? Recno { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DocumentNumber")]
        public string DocumentNumber { get; set; }

    }
}
