// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class GetDocumentsArgsParameterDateCriteriaItem
    {
        /// <summary>
        /// Initializes a new instance of the
        /// GetDocumentsArgsParameterDateCriteriaItem class.
        /// </summary>
        public GetDocumentsArgsParameterDateCriteriaItem() { }

        /// <summary>
        /// Initializes a new instance of the
        /// GetDocumentsArgsParameterDateCriteriaItem class.
        /// </summary>
        public GetDocumentsArgsParameterDateCriteriaItem(string dateName = default(string), string operatorProperty = default(string), DateTime? dateValue = default(DateTime?))
        {
            DateName = dateName;
            OperatorProperty = operatorProperty;
            DateValue = dateValue;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateName")]
        public string DateName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Operator")]
        public string OperatorProperty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateValue")]
        public DateTime? DateValue { get; set; }

    }
}
