// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class GetDocumentsOKResponseDocumentsItemResponsiblePerson
    {
        /// <summary>
        /// Initializes a new instance of the
        /// GetDocumentsOKResponseDocumentsItemResponsiblePerson class.
        /// </summary>
        public GetDocumentsOKResponseDocumentsItemResponsiblePerson() { }

        /// <summary>
        /// Initializes a new instance of the
        /// GetDocumentsOKResponseDocumentsItemResponsiblePerson class.
        /// </summary>
        public GetDocumentsOKResponseDocumentsItemResponsiblePerson(string email = default(string), string userId = default(string), int? recno = default(int?), string externalId = default(string), string referencenumber = default(string), string name = default(string), string url = default(string), int? domain = default(int?))
        {
            Email = email;
            UserId = userId;
            Recno = recno;
            ExternalId = externalId;
            Referencenumber = referencenumber;
            Name = name;
            Url = url;
            Domain = domain;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UserId")]
        public string UserId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Recno")]
        public int? Recno { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ExternalId")]
        public string ExternalId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Referencenumber")]
        public string Referencenumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Domain")]
        public int? Domain { get; set; }

    }
}
