// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class GetDocumentsArgs
    {
        /// <summary>
        /// Initializes a new instance of the GetDocumentsArgs class.
        /// </summary>
        public GetDocumentsArgs() { }

        /// <summary>
        /// Initializes a new instance of the GetDocumentsArgs class.
        /// </summary>
        public GetDocumentsArgs(GetDocumentsArgsParameter parameter = default(GetDocumentsArgsParameter))
        {
            Parameter = parameter;
        }

        /// <summary>
        /// GetDocumentsQuery parameter containing document details
        /// </summary>
        [JsonProperty(PropertyName = "parameter")]
        public GetDocumentsArgsParameter Parameter { get; set; }

    }
}
