// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class GetDocumentsOKResponseDocumentsItemType
    {
        /// <summary>
        /// Initializes a new instance of the
        /// GetDocumentsOKResponseDocumentsItemType class.
        /// </summary>
        public GetDocumentsOKResponseDocumentsItemType() { }

        /// <summary>
        /// Initializes a new instance of the
        /// GetDocumentsOKResponseDocumentsItemType class.
        /// </summary>
        public GetDocumentsOKResponseDocumentsItemType(int? recno = default(int?), string code = default(string), string description = default(string))
        {
            Recno = recno;
            Code = code;
            Description = description;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Recno")]
        public int? Recno { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Code")]
        public string Code { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Description")]
        public string Description { get; set; }

    }
}
