// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class UpdateDocumentArgs
    {
        /// <summary>
        /// Initializes a new instance of the UpdateDocumentArgs class.
        /// </summary>
        public UpdateDocumentArgs() { }

        /// <summary>
        /// Initializes a new instance of the UpdateDocumentArgs class.
        /// </summary>
        public UpdateDocumentArgs(UpdateDocumentArgsParameter parameter = default(UpdateDocumentArgsParameter))
        {
            Parameter = parameter;
        }

        /// <summary>
        /// UpdateDocumentParameter with metadata to update document
        /// </summary>
        [JsonProperty(PropertyName = "parameter")]
        public UpdateDocumentArgsParameter Parameter { get; set; }

    }
}
