// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// GetUsersParameter containing the ADContextUser, UserId and
    /// ContactExternalId
    /// </summary>
    public partial class GetUsersArgsParameter
    {
        /// <summary>
        /// Initializes a new instance of the GetUsersArgsParameter class.
        /// </summary>
        public GetUsersArgsParameter() { }

        /// <summary>
        /// Initializes a new instance of the GetUsersArgsParameter class.
        /// </summary>
        public GetUsersArgsParameter(string aDContextUser = default(string), string userId = default(string), string contactExternalId = default(string), int? contactRecno = default(int?))
        {
            ADContextUser = aDContextUser;
            UserId = userId;
            ContactExternalId = contactExternalId;
            ContactRecno = contactRecno;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ADContextUser")]
        public string ADContextUser { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UserId")]
        public string UserId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ContactExternalId")]
        public string ContactExternalId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ContactRecno")]
        public int? ContactRecno { get; set; }

    }
}
