// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class GetUsersOKResponseUsersItemProfilesItem
    {
        /// <summary>
        /// Initializes a new instance of the
        /// GetUsersOKResponseUsersItemProfilesItem class.
        /// </summary>
        public GetUsersOKResponseUsersItemProfilesItem() { }

        /// <summary>
        /// Initializes a new instance of the
        /// GetUsersOKResponseUsersItemProfilesItem class.
        /// </summary>
        public GetUsersOKResponseUsersItemProfilesItem(string role = default(string), string enterpriseId = default(string), DateTime? fromDate = default(DateTime?), DateTime? toDate = default(DateTime?))
        {
            Role = role;
            EnterpriseId = enterpriseId;
            FromDate = fromDate;
            ToDate = toDate;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Role")]
        public string Role { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EnterpriseId")]
        public string EnterpriseId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FromDate")]
        public DateTime? FromDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ToDate")]
        public DateTime? ToDate { get; set; }

    }
}
