// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// SynchronizeUserParameter
    /// </summary>
    public partial class SynchronizeUserArgsParameter
    {
        /// <summary>
        /// Initializes a new instance of the SynchronizeUserArgsParameter
        /// class.
        /// </summary>
        public SynchronizeUserArgsParameter() { }

        /// <summary>
        /// Initializes a new instance of the SynchronizeUserArgsParameter
        /// class.
        /// </summary>
        public SynchronizeUserArgsParameter(string aDContextUser = default(string), string login = default(string), string contactExternalId = default(string), bool? isActive = default(bool?), bool? isServiceUser = default(bool?), IList<SynchronizeUserArgsParameterProfilesItem> profiles = default(IList<SynchronizeUserArgsParameterProfilesItem>), IList<SynchronizeUserArgsParameterAccessGroupsItem> accessGroups = default(IList<SynchronizeUserArgsParameterAccessGroupsItem>), int? contactRecno = default(int?))
        {
            ADContextUser = aDContextUser;
            Login = login;
            ContactExternalId = contactExternalId;
            IsActive = isActive;
            IsServiceUser = isServiceUser;
            Profiles = profiles;
            AccessGroups = accessGroups;
            ContactRecno = contactRecno;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ADContextUser")]
        public string ADContextUser { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Login")]
        public string Login { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ContactExternalId")]
        public string ContactExternalId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsActive")]
        public bool? IsActive { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsServiceUser")]
        public bool? IsServiceUser { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Profiles")]
        public IList<SynchronizeUserArgsParameterProfilesItem> Profiles { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccessGroups")]
        public IList<SynchronizeUserArgsParameterAccessGroupsItem> AccessGroups { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ContactRecno")]
        public int? ContactRecno { get; set; }

    }
}
