// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class GetCodeTableRowsArgs
    {
        /// <summary>
        /// Initializes a new instance of the GetCodeTableRowsArgs class.
        /// </summary>
        public GetCodeTableRowsArgs() { }

        /// <summary>
        /// Initializes a new instance of the GetCodeTableRowsArgs class.
        /// </summary>
        public GetCodeTableRowsArgs(GetCodeTableRowsArgsParameter parameter = default(GetCodeTableRowsArgsParameter))
        {
            Parameter = parameter;
        }

        /// <summary>
        /// GetCodeTableRowsQuery
        /// </summary>
        [JsonProperty(PropertyName = "parameter")]
        public GetCodeTableRowsArgsParameter Parameter { get; set; }

    }
}
