// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// GetEventsQuery
    /// </summary>
    public partial class GetEventsArgsParameter
    {
        /// <summary>
        /// Initializes a new instance of the GetEventsArgsParameter class.
        /// </summary>
        public GetEventsArgsParameter() { }

        /// <summary>
        /// Initializes a new instance of the GetEventsArgsParameter class.
        /// </summary>
        public GetEventsArgsParameter(int? recno = default(int?), int? logCount = default(int?), DateTime? fromDate = default(DateTime?), DateTime? toDate = default(DateTime?))
        {
            Recno = recno;
            LogCount = logCount;
            FromDate = fromDate;
            ToDate = toDate;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Recno")]
        public int? Recno { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LogCount")]
        public int? LogCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FromDate")]
        public DateTime? FromDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ToDate")]
        public DateTime? ToDate { get; set; }

    }
}
