// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class GetEventsArgs
    {
        /// <summary>
        /// Initializes a new instance of the GetEventsArgs class.
        /// </summary>
        public GetEventsArgs() { }

        /// <summary>
        /// Initializes a new instance of the GetEventsArgs class.
        /// </summary>
        public GetEventsArgs(GetEventsArgsParameter parameter = default(GetEventsArgsParameter))
        {
            Parameter = parameter;
        }

        /// <summary>
        /// GetEventsQuery
        /// </summary>
        [JsonProperty(PropertyName = "parameter")]
        public GetEventsArgsParameter Parameter { get; set; }

    }
}
