// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class GetEventsOKResponseEventsItem
    {
        /// <summary>
        /// Initializes a new instance of the GetEventsOKResponseEventsItem
        /// class.
        /// </summary>
        public GetEventsOKResponseEventsItem() { }

        /// <summary>
        /// Initializes a new instance of the GetEventsOKResponseEventsItem
        /// class.
        /// </summary>
        public GetEventsOKResponseEventsItem(int? recno = default(int?), string type = default(string), string entityName = default(string), string entityRecno = default(string), DateTime? insertedDate = default(DateTime?), object data = default(object))
        {
            Recno = recno;
            Type = type;
            EntityName = entityName;
            EntityRecno = entityRecno;
            InsertedDate = insertedDate;
            Data = data;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Recno")]
        public int? Recno { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EntityName")]
        public string EntityName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EntityRecno")]
        public string EntityRecno { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "InsertedDate")]
        public DateTime? InsertedDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Data")]
        public object Data { get; set; }

    }
}
