// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class GetLogsArgs
    {
        /// <summary>
        /// Initializes a new instance of the GetLogsArgs class.
        /// </summary>
        public GetLogsArgs() { }

        /// <summary>
        /// Initializes a new instance of the GetLogsArgs class.
        /// </summary>
        public GetLogsArgs(GetLogsArgsParameter parameter = default(GetLogsArgsParameter))
        {
            Parameter = parameter;
        }

        /// <summary>
        /// GetLogsQuery
        /// </summary>
        [JsonProperty(PropertyName = "parameter")]
        public GetLogsArgsParameter Parameter { get; set; }

    }
}
