// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CheckOutAndGetFileForExternalControlOKResponse
    {
        /// <summary>
        /// Initializes a new instance of the
        /// CheckOutAndGetFileForExternalControlOKResponse class.
        /// </summary>
        public CheckOutAndGetFileForExternalControlOKResponse() { }

        /// <summary>
        /// Initializes a new instance of the
        /// CheckOutAndGetFileForExternalControlOKResponse class.
        /// </summary>
        public CheckOutAndGetFileForExternalControlOKResponse(CheckOutAndGetFileForExternalControlOKResponseCheckOutFileInfo checkOutFileInfo = default(CheckOutAndGetFileForExternalControlOKResponseCheckOutFileInfo), IList<object> fileData = default(IList<object>))
        {
            CheckOutFileInfo = checkOutFileInfo;
            FileData = fileData;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CheckOutFileInfo")]
        public CheckOutAndGetFileForExternalControlOKResponseCheckOutFileInfo CheckOutFileInfo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FileData")]
        public IList<object> FileData { get; set; }

    }
}
