// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CheckOutAndGetFileForExternalControlArgs
    {
        /// <summary>
        /// Initializes a new instance of the
        /// CheckOutAndGetFileForExternalControlArgs class.
        /// </summary>
        public CheckOutAndGetFileForExternalControlArgs() { }

        /// <summary>
        /// Initializes a new instance of the
        /// CheckOutAndGetFileForExternalControlArgs class.
        /// </summary>
        public CheckOutAndGetFileForExternalControlArgs(CheckOutAndGetFileForExternalControlArgsMessage message = default(CheckOutAndGetFileForExternalControlArgsMessage))
        {
            Message = message;
        }

        /// <summary>
        /// CheckOutAndGetFileForExternalControlMessage parameter containing
        /// User, ExternalSystem and FileRecno.
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public CheckOutAndGetFileForExternalControlArgsMessage Message { get; set; }

    }
}
