// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// FileParameterBase parameter containing Document and ADContextUser
    /// </summary>
    public partial class CreateFileArgsParameter
    {
        /// <summary>
        /// Initializes a new instance of the CreateFileArgsParameter class.
        /// </summary>
        public CreateFileArgsParameter() { }

        /// <summary>
        /// Initializes a new instance of the CreateFileArgsParameter class.
        /// </summary>
        public CreateFileArgsParameter(string aDContextUser = default(string), int? documentRecno = default(int?), string documentNumber = default(string), string title = default(string), string format = default(string), string base64Data = default(string), IList<object> data = default(IList<object>), string relationType = default(string), string versionFormat = default(string), string note = default(string), string category = default(string), string status = default(string), string accessCode = default(string), string degradeCode = default(string), DateTime? degradeDate = default(DateTime?), bool? filedOnPaper = default(bool?), string paperLocation = default(string), string uploadedFileReference = default(string), IList<CreateFileArgsParameterAdditionalFieldsItem> additionalFields = default(IList<CreateFileArgsParameterAdditionalFieldsItem>))
        {
            ADContextUser = aDContextUser;
            DocumentRecno = documentRecno;
            DocumentNumber = documentNumber;
            Title = title;
            Format = format;
            Base64Data = base64Data;
            Data = data;
            RelationType = relationType;
            VersionFormat = versionFormat;
            Note = note;
            Category = category;
            Status = status;
            AccessCode = accessCode;
            DegradeCode = degradeCode;
            DegradeDate = degradeDate;
            FiledOnPaper = filedOnPaper;
            PaperLocation = paperLocation;
            UploadedFileReference = uploadedFileReference;
            AdditionalFields = additionalFields;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ADContextUser")]
        public string ADContextUser { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DocumentRecno")]
        public int? DocumentRecno { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DocumentNumber")]
        public string DocumentNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Format")]
        public string Format { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Base64Data")]
        public string Base64Data { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Data")]
        public IList<object> Data { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RelationType")]
        public string RelationType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "VersionFormat")]
        public string VersionFormat { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Note")]
        public string Note { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Category")]
        public string Category { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Status")]
        public string Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccessCode")]
        public string AccessCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DegradeCode")]
        public string DegradeCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DegradeDate")]
        public DateTime? DegradeDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FiledOnPaper")]
        public bool? FiledOnPaper { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PaperLocation")]
        public string PaperLocation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UploadedFileReference")]
        public string UploadedFileReference { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AdditionalFields")]
        public IList<CreateFileArgsParameterAdditionalFieldsItem> AdditionalFields { get; set; }

    }
}
