// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class DeleteFileArgs
    {
        /// <summary>
        /// Initializes a new instance of the DeleteFileArgs class.
        /// </summary>
        public DeleteFileArgs() { }

        /// <summary>
        /// Initializes a new instance of the DeleteFileArgs class.
        /// </summary>
        public DeleteFileArgs(DeleteFileArgsParameter parameter = default(DeleteFileArgsParameter))
        {
            Parameter = parameter;
        }

        /// <summary>
        /// DeleteFileParameter parameter containing Recno of file
        /// </summary>
        [JsonProperty(PropertyName = "parameter")]
        public DeleteFileArgsParameter Parameter { get; set; }

    }
}
