// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class GetFileWithMetadataArgs
    {
        /// <summary>
        /// Initializes a new instance of the GetFileWithMetadataArgs class.
        /// </summary>
        public GetFileWithMetadataArgs() { }

        /// <summary>
        /// Initializes a new instance of the GetFileWithMetadataArgs class.
        /// </summary>
        public GetFileWithMetadataArgs(GetFileWithMetadataArgsParameter parameter = default(GetFileWithMetadataArgsParameter))
        {
            Parameter = parameter;
        }

        /// <summary>
        /// GetFileWithMetadataQuery parameter containing Recno,
        /// IncludeFileData and ADContextUser
        /// </summary>
        [JsonProperty(PropertyName = "parameter")]
        public GetFileWithMetadataArgsParameter Parameter { get; set; }

    }
}
