// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class GetFileOKResponseRequestMessage
    {
        /// <summary>
        /// Initializes a new instance of the GetFileOKResponseRequestMessage
        /// class.
        /// </summary>
        public GetFileOKResponseRequestMessage() { }

        /// <summary>
        /// Initializes a new instance of the GetFileOKResponseRequestMessage
        /// class.
        /// </summary>
        public GetFileOKResponseRequestMessage(GetFileOKResponseRequestMessageVersion version = default(GetFileOKResponseRequestMessageVersion), GetFileOKResponseRequestMessageContent content = default(GetFileOKResponseRequestMessageContent), GetFileOKResponseRequestMessageMethod method = default(GetFileOKResponseRequestMessageMethod), GetFileOKResponseRequestMessageRequestUri requestUri = default(GetFileOKResponseRequestMessageRequestUri), IList<GetFileOKResponseRequestMessageHeadersItem> headers = default(IList<GetFileOKResponseRequestMessageHeadersItem>), IList<GetFileOKResponseRequestMessagePropertiesItem> properties = default(IList<GetFileOKResponseRequestMessagePropertiesItem>))
        {
            Version = version;
            Content = content;
            Method = method;
            RequestUri = requestUri;
            Headers = headers;
            Properties = properties;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Version")]
        public GetFileOKResponseRequestMessageVersion Version { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Content")]
        public GetFileOKResponseRequestMessageContent Content { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Method")]
        public GetFileOKResponseRequestMessageMethod Method { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RequestUri")]
        public GetFileOKResponseRequestMessageRequestUri RequestUri { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Headers")]
        public IList<GetFileOKResponseRequestMessageHeadersItem> Headers { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Properties")]
        public IList<GetFileOKResponseRequestMessagePropertiesItem> Properties { get; set; }

    }
}
