// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class GetFileOKResponseRequestMessageContent
    {
        /// <summary>
        /// Initializes a new instance of the
        /// GetFileOKResponseRequestMessageContent class.
        /// </summary>
        public GetFileOKResponseRequestMessageContent() { }

        /// <summary>
        /// Initializes a new instance of the
        /// GetFileOKResponseRequestMessageContent class.
        /// </summary>
        public GetFileOKResponseRequestMessageContent(IList<GetFileOKResponseRequestMessageContentHeadersItem> headers = default(IList<GetFileOKResponseRequestMessageContentHeadersItem>))
        {
            Headers = headers;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Headers")]
        public IList<GetFileOKResponseRequestMessageContentHeadersItem> Headers { get; set; }

    }
}
