// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// GetFileWithMetadataQuery parameter containing Recno, IncludeFileData
    /// and ADContextUser
    /// </summary>
    public partial class GetFileWithMetadataArgsParameter
    {
        /// <summary>
        /// Initializes a new instance of the GetFileWithMetadataArgsParameter
        /// class.
        /// </summary>
        public GetFileWithMetadataArgsParameter() { }

        /// <summary>
        /// Initializes a new instance of the GetFileWithMetadataArgsParameter
        /// class.
        /// </summary>
        public GetFileWithMetadataArgsParameter(int? recno = default(int?), bool? includeFileData = default(bool?), string aDContextUser = default(string), bool? includeCustomFields = default(bool?))
        {
            Recno = recno;
            IncludeFileData = includeFileData;
            ADContextUser = aDContextUser;
            IncludeCustomFields = includeCustomFields;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Recno")]
        public int? Recno { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IncludeFileData")]
        public bool? IncludeFileData { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ADContextUser")]
        public string ADContextUser { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IncludeCustomFields")]
        public bool? IncludeCustomFields { get; set; }

    }
}
