// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// GetFileQuery parameter containing Recno and ADContextUser
    /// </summary>
    public partial class GetFileArgsParameter
    {
        /// <summary>
        /// Initializes a new instance of the GetFileArgsParameter class.
        /// </summary>
        public GetFileArgsParameter() { }

        /// <summary>
        /// Initializes a new instance of the GetFileArgsParameter class.
        /// </summary>
        public GetFileArgsParameter(int? recno = default(int?), string aDContextUser = default(string))
        {
            Recno = recno;
            ADContextUser = aDContextUser;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Recno")]
        public int? Recno { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ADContextUser")]
        public string ADContextUser { get; set; }

    }
}
