// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class UploadArgs
    {
        /// <summary>
        /// Initializes a new instance of the UploadArgs class.
        /// </summary>
        public UploadArgs() { }

        /// <summary>
        /// Initializes a new instance of the UploadArgs class.
        /// </summary>
        public UploadArgs(UploadArgsParameter parameter = default(UploadArgsParameter))
        {
            Parameter = parameter;
        }

        /// <summary>
        /// FileUploadMessageRPC parameter containing User, FileData, FileName
        /// and FileFormat
        /// </summary>
        [JsonProperty(PropertyName = "parameter")]
        public UploadArgsParameter Parameter { get; set; }

    }
}
