// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// FileUploadMessageRPC parameter containing User, FileData, FileName and
    /// FileFormat
    /// </summary>
    public partial class UploadArgsParameter
    {
        /// <summary>
        /// Initializes a new instance of the UploadArgsParameter class.
        /// </summary>
        public UploadArgsParameter() { }

        /// <summary>
        /// Initializes a new instance of the UploadArgsParameter class.
        /// </summary>
        public UploadArgsParameter(string aDContextUser = default(string),string user = default(string), IList<object> fileData = default(IList<object>), string fileName = default(string), string fileFormat = default(string))
        {
            ADContextUser = aDContextUser;
            User = user;
            FileData = fileData;
            FileName = fileName;
            FileFormat = fileFormat;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ADContextUser")]
        public string ADContextUser { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "User")]
        public string User { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FileData")]
        public IList<object> FileData { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FileName")]
        public string FileName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FileFormat")]
        public string FileFormat { get; set; }

    }
}
