// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class UploadAndCheckInFileFromExternalControlArgsMessageCheckInFileInfo
    {
        /// <summary>
        /// Initializes a new instance of the
        /// UploadAndCheckInFileFromExternalControlArgsMessageCheckInFileInfo
        /// class.
        /// </summary>
        public UploadAndCheckInFileFromExternalControlArgsMessageCheckInFileInfo() { }

        /// <summary>
        /// Initializes a new instance of the
        /// UploadAndCheckInFileFromExternalControlArgsMessageCheckInFileInfo
        /// class.
        /// </summary>
        public UploadAndCheckInFileFromExternalControlArgsMessageCheckInFileInfo(string fileRecno = default(string), string title = default(string), string fileFormat = default(string), string user = default(string), string externalSystem = default(string))
        {
            FileRecno = fileRecno;
            Title = title;
            FileFormat = fileFormat;
            User = user;
            ExternalSystem = externalSystem;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FileRecno")]
        public string FileRecno { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FileFormat")]
        public string FileFormat { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "User")]
        public string User { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ExternalSystem")]
        public string ExternalSystem { get; set; }

    }
}
