// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class UploadAndCheckInFileFromExternalControlArgs
    {
        /// <summary>
        /// Initializes a new instance of the
        /// UploadAndCheckInFileFromExternalControlArgs class.
        /// </summary>
        public UploadAndCheckInFileFromExternalControlArgs() { }

        /// <summary>
        /// Initializes a new instance of the
        /// UploadAndCheckInFileFromExternalControlArgs class.
        /// </summary>
        public UploadAndCheckInFileFromExternalControlArgs(UploadAndCheckInFileFromExternalControlArgsMessage message = default(UploadAndCheckInFileFromExternalControlArgsMessage))
        {
            Message = message;
        }

        /// <summary>
        /// UploadAndCheckInFileFromExternalControlMessage parameter
        /// containing CheckInFileInfo and FileStream
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public UploadAndCheckInFileFromExternalControlArgsMessage Message { get; set; }

    }
}
