// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// UploadAndCheckInFileFromExternalControlMessage parameter containing
    /// CheckInFileInfo and FileStream
    /// </summary>
    public partial class UploadAndCheckInFileFromExternalControlArgsMessage
    {
        /// <summary>
        /// Initializes a new instance of the
        /// UploadAndCheckInFileFromExternalControlArgsMessage class.
        /// </summary>
        public UploadAndCheckInFileFromExternalControlArgsMessage() { }

        /// <summary>
        /// Initializes a new instance of the
        /// UploadAndCheckInFileFromExternalControlArgsMessage class.
        /// </summary>
        public UploadAndCheckInFileFromExternalControlArgsMessage(UploadAndCheckInFileFromExternalControlArgsMessageCheckInFileInfo checkInFileInfo = default(UploadAndCheckInFileFromExternalControlArgsMessageCheckInFileInfo), IList<object> fileData = default(IList<object>))
        {
            CheckInFileInfo = checkInFileInfo;
            FileData = fileData;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CheckInFileInfo")]
        public UploadAndCheckInFileFromExternalControlArgsMessageCheckInFileInfo CheckInFileInfo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FileData")]
        public IList<object> FileData { get; set; }

    }
}
