// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// CreateProjectParameter
    /// </summary>
    public partial class CreateProjectArgsParameter
    {
        /// <summary>
        /// Initializes a new instance of the CreateProjectArgsParameter class.
        /// </summary>
        public CreateProjectArgsParameter() { }

        /// <summary>
        /// Initializes a new instance of the CreateProjectArgsParameter class.
        /// </summary>
        public CreateProjectArgsParameter(string type = default(string), string aDContextUser = default(string), CreateProjectArgsParameterExternalId externalId = default(CreateProjectArgsParameterExternalId), string title = default(string), string category = default(string), string status = default(string), DateTime? startDate = default(DateTime?), DateTime? endDate = default(DateTime?), string accessGroup = default(string), string notes = default(string), int? responsiblePersonRecno = default(int?), string responsiblePersonIdNumber = default(string), string responsiblePersonEmail = default(string), string responsiblePersonUserId = default(string), IList<CreateProjectArgsParameterAdditionalFieldsItem> additionalFields = default(IList<CreateProjectArgsParameterAdditionalFieldsItem>), IList<CreateProjectArgsParameterEstatesItem> estates = default(IList<CreateProjectArgsParameterEstatesItem>), IList<CreateProjectArgsParameterContactsItem> contacts = default(IList<CreateProjectArgsParameterContactsItem>))
        {
            Type = type;
            ADContextUser = aDContextUser;
            ExternalId = externalId;
            Title = title;
            Category = category;
            Status = status;
            StartDate = startDate;
            EndDate = endDate;
            AccessGroup = accessGroup;
            Notes = notes;
            ResponsiblePersonRecno = responsiblePersonRecno;
            ResponsiblePersonIdNumber = responsiblePersonIdNumber;
            ResponsiblePersonEmail = responsiblePersonEmail;
            ResponsiblePersonUserId = responsiblePersonUserId;
            AdditionalFields = additionalFields;
            Estates = estates;
            Contacts = contacts;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ADContextUser")]
        public string ADContextUser { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ExternalId")]
        public CreateProjectArgsParameterExternalId ExternalId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Category")]
        public string Category { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Status")]
        public string Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "StartDate")]
        public DateTime? StartDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EndDate")]
        public DateTime? EndDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccessGroup")]
        public string AccessGroup { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Notes")]
        public string Notes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ResponsiblePersonRecno")]
        public int? ResponsiblePersonRecno { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ResponsiblePersonIdNumber")]
        public string ResponsiblePersonIdNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ResponsiblePersonEmail")]
        public string ResponsiblePersonEmail { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ResponsiblePersonUserId")]
        public string ResponsiblePersonUserId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AdditionalFields")]
        public IList<CreateProjectArgsParameterAdditionalFieldsItem> AdditionalFields { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Estates")]
        public IList<CreateProjectArgsParameterEstatesItem> Estates { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Contacts")]
        public IList<CreateProjectArgsParameterContactsItem> Contacts { get; set; }

    }
}
