// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class UpdateProjectArgs
    {
        /// <summary>
        /// Initializes a new instance of the UpdateProjectArgs class.
        /// </summary>
        public UpdateProjectArgs() { }

        /// <summary>
        /// Initializes a new instance of the UpdateProjectArgs class.
        /// </summary>
        public UpdateProjectArgs(UpdateProjectArgsParameter parameter = default(UpdateProjectArgsParameter))
        {
            Parameter = parameter;
        }

        /// <summary>
        /// UpdateProjectParameter
        /// </summary>
        [JsonProperty(PropertyName = "parameter")]
        public UpdateProjectArgsParameter Parameter { get; set; }

    }
}
