// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class UpdateProjectArgsParameterContactsItem
    {
        /// <summary>
        /// Initializes a new instance of the
        /// UpdateProjectArgsParameterContactsItem class.
        /// </summary>
        public UpdateProjectArgsParameterContactsItem() { }

        /// <summary>
        /// Initializes a new instance of the
        /// UpdateProjectArgsParameterContactsItem class.
        /// </summary>
        public UpdateProjectArgsParameterContactsItem(string role = default(string), string externalId = default(string), string referenceNumber = default(string))
        {
            Role = role;
            ExternalId = externalId;
            ReferenceNumber = referenceNumber;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Role")]
        public string Role { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ExternalId")]
        public string ExternalId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ReferenceNumber")]
        public string ReferenceNumber { get; set; }

    }
}
