// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CreateCaseArgsParameterRemarksItem
    {
        /// <summary>
        /// Initializes a new instance of the
        /// CreateCaseArgsParameterRemarksItem class.
        /// </summary>
        public CreateCaseArgsParameterRemarksItem() { }

        /// <summary>
        /// Initializes a new instance of the
        /// CreateCaseArgsParameterRemarksItem class.
        /// </summary>
        public CreateCaseArgsParameterRemarksItem(string title = default(string), string content = default(string), string remarkType = default(string))
        {
            Title = title;
            Content = content;
            RemarkType = remarkType;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Content")]
        public string Content { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RemarkType")]
        public string RemarkType { get; set; }

    }
}
