// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class GetCasesOKResponseCasesItemProgressPlan
    {
        /// <summary>
        /// Initializes a new instance of the
        /// GetCasesOKResponseCasesItemProgressPlan class.
        /// </summary>
        public GetCasesOKResponseCasesItemProgressPlan() { }

        /// <summary>
        /// Initializes a new instance of the
        /// GetCasesOKResponseCasesItemProgressPlan class.
        /// </summary>
        public GetCasesOKResponseCasesItemProgressPlan(string recno = default(string), string description = default(string), string workunitID = default(string))
        {
            Recno = recno;
            Description = description;
            WorkunitID = workunitID;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Recno")]
        public string Recno { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "WorkunitID")]
        public string WorkunitID { get; set; }

    }
}
