// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// GetContactPersonsParameter.
    /// </summary>
    public partial class GetContactPersonsArgsParameter
    {
        /// <summary>
        /// Initializes a new instance of the GetContactPersonsArgsParameter
        /// class.
        /// </summary>
        public GetContactPersonsArgsParameter() { }

        /// <summary>
        /// Initializes a new instance of the GetContactPersonsArgsParameter
        /// class.
        /// </summary>
        public GetContactPersonsArgsParameter(string aDContextUser = default(string), int? recno = default(int?), string name = default(string), string externalId = default(string), bool? active = default(bool?), IList<string> categories = default(IList<string>), GetContactPersonsArgsParameterCreatedDateRange createdDateRange = default(GetContactPersonsArgsParameterCreatedDateRange), GetContactPersonsArgsParameterModifiedDateRange modifiedDateRange = default(GetContactPersonsArgsParameterModifiedDateRange), int? page = default(int?), int? maxRows = default(int?), string sortCriterion = default(string), IList<GetContactPersonsArgsParameterAdditionalFieldsItem> additionalFields = default(IList<GetContactPersonsArgsParameterAdditionalFieldsItem>), bool? includeCustomFields = default(bool?), IList<GetContactPersonsArgsParameterDateCriteriaItem> dateCriteria = default(IList<GetContactPersonsArgsParameterDateCriteriaItem>), string email = default(string), string alternativeEmail = default(string), IList<GetContactPersonsArgsParameterAdditionalListFieldsItem> additionalListFields = default(IList<GetContactPersonsArgsParameterAdditionalListFieldsItem>))
        {
            ADContextUser = aDContextUser;
            Recno = recno;
            Name = name;
            ExternalId = externalId;
            Active = active;
            Categories = categories;
            CreatedDateRange = createdDateRange;
            ModifiedDateRange = modifiedDateRange;
            Page = page;
            MaxRows = maxRows;
            SortCriterion = sortCriterion;
            AdditionalFields = additionalFields;
            IncludeCustomFields = includeCustomFields;
            DateCriteria = dateCriteria;
            Email = email;
            AlternativeEmail = alternativeEmail;
            AdditionalListFields = additionalListFields;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ADContextUser")]
        public string ADContextUser { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Recno")]
        public int? Recno { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ExternalId")]
        public string ExternalId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Active")]
        public bool? Active { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Categories")]
        public IList<string> Categories { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CreatedDateRange")]
        public GetContactPersonsArgsParameterCreatedDateRange CreatedDateRange { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ModifiedDateRange")]
        public GetContactPersonsArgsParameterModifiedDateRange ModifiedDateRange { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Page")]
        public int? Page { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MaxRows")]
        public int? MaxRows { get; set; }

        /// <summary>
        /// Possible values include: 'RecnoDescending', 'RecnoAscending'
        /// </summary>
        [JsonProperty(PropertyName = "SortCriterion")]
        public string SortCriterion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AdditionalFields")]
        public IList<GetContactPersonsArgsParameterAdditionalFieldsItem> AdditionalFields { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IncludeCustomFields")]
        public bool? IncludeCustomFields { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateCriteria")]
        public IList<GetContactPersonsArgsParameterDateCriteriaItem> DateCriteria { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AlternativeEmail")]
        public string AlternativeEmail { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AdditionalListFields")]
        public IList<GetContactPersonsArgsParameterAdditionalListFieldsItem> AdditionalListFields { get; set; }

    }
}
