// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// GetEnterprisesParameter.
    /// </summary>
    public partial class GetEnterprisesArgsParameter
    {
        /// <summary>
        /// Initializes a new instance of the GetEnterprisesArgsParameter
        /// class.
        /// </summary>
        public GetEnterprisesArgsParameter() { }

        /// <summary>
        /// Initializes a new instance of the GetEnterprisesArgsParameter
        /// class.
        /// </summary>
        public GetEnterprisesArgsParameter(string aDContextUser = default(string), int? recno = default(int?), string name = default(string), string externalID = default(string), string enterpriseNumber = default(string), bool? active = default(bool?), IList<string> categories = default(IList<string>), GetEnterprisesArgsParameterCreatedDateRange createdDateRange = default(GetEnterprisesArgsParameterCreatedDateRange), GetEnterprisesArgsParameterModifiedDateRange modifiedDateRange = default(GetEnterprisesArgsParameterModifiedDateRange), int? page = default(int?), int? maxRows = default(int?), string sortCriterion = default(string), string initials = default(string), IList<GetEnterprisesArgsParameterAdditionalFieldsItem> additionalFields = default(IList<GetEnterprisesArgsParameterAdditionalFieldsItem>), bool? includeCustomFields = default(bool?), IList<GetEnterprisesArgsParameterDateCriteriaItem> dateCriteria = default(IList<GetEnterprisesArgsParameterDateCriteriaItem>), string email = default(string), string alternativeEmail = default(string), IList<GetEnterprisesArgsParameterAdditionalListFieldsItem> additionalListFields = default(IList<GetEnterprisesArgsParameterAdditionalListFieldsItem>))
        {
            ADContextUser = aDContextUser;
            Recno = recno;
            Name = name;
            ExternalID = externalID;
            EnterpriseNumber = enterpriseNumber;
            Active = active;
            Categories = categories;
            CreatedDateRange = createdDateRange;
            ModifiedDateRange = modifiedDateRange;
            Page = page;
            MaxRows = maxRows;
            SortCriterion = sortCriterion;
            Initials = initials;
            AdditionalFields = additionalFields;
            IncludeCustomFields = includeCustomFields;
            DateCriteria = dateCriteria;
            Email = email;
            AlternativeEmail = alternativeEmail;
            AdditionalListFields = additionalListFields;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ADContextUser")]
        public string ADContextUser { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Recno")]
        public int? Recno { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ExternalID")]
        public string ExternalID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EnterpriseNumber")]
        public string EnterpriseNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Active")]
        public bool? Active { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Categories")]
        public IList<string> Categories { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CreatedDateRange")]
        public GetEnterprisesArgsParameterCreatedDateRange CreatedDateRange { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ModifiedDateRange")]
        public GetEnterprisesArgsParameterModifiedDateRange ModifiedDateRange { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Page")]
        public int? Page { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MaxRows")]
        public int? MaxRows { get; set; }

        /// <summary>
        /// Possible values include: 'RecnoDescending', 'RecnoAscending'
        /// </summary>
        [JsonProperty(PropertyName = "SortCriterion")]
        public string SortCriterion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Initials")]
        public string Initials { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AdditionalFields")]
        public IList<GetEnterprisesArgsParameterAdditionalFieldsItem> AdditionalFields { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IncludeCustomFields")]
        public bool? IncludeCustomFields { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateCriteria")]
        public IList<GetEnterprisesArgsParameterDateCriteriaItem> DateCriteria { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AlternativeEmail")]
        public string AlternativeEmail { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AdditionalListFields")]
        public IList<GetEnterprisesArgsParameterAdditionalListFieldsItem> AdditionalListFields { get; set; }

    }
}
