// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class GetEnterprisesOKResponseEnterprisesItem
    {
        /// <summary>
        /// Initializes a new instance of the
        /// GetEnterprisesOKResponseEnterprisesItem class.
        /// </summary>
        public GetEnterprisesOKResponseEnterprisesItem() { }

        /// <summary>
        /// Initializes a new instance of the
        /// GetEnterprisesOKResponseEnterprisesItem class.
        /// </summary>
        public GetEnterprisesOKResponseEnterprisesItem(int? recno = default(int?), object contactRelations = default(object), string enterpriseNumber = default(string), string externalID = default(string), string name = default(string), string telefax = default(string), string mobilePhone = default(string), string phoneNumber = default(string), string email = default(string), GetEnterprisesOKResponseEnterprisesItemPostAddress postAddress = default(GetEnterprisesOKResponseEnterprisesItemPostAddress), GetEnterprisesOKResponseEnterprisesItemOfficeAddress officeAddress = default(GetEnterprisesOKResponseEnterprisesItemOfficeAddress), string initials = default(string), string web = default(string), IList<string> categories = default(IList<string>), string parentEnterpriseNumber = default(string), string customNo1 = default(string), string customNo2 = default(string), string customNo3 = default(string), bool? active = default(bool?), DateTime? createdDate = default(DateTime?), DateTime? modifiedDate = default(DateTime?), string accessGroup = default(string), object additionalFields = default(object), string alternativeEmail = default(string))
        {
            Recno = recno;
            ContactRelations = contactRelations;
            EnterpriseNumber = enterpriseNumber;
            ExternalID = externalID;
            Name = name;
            Telefax = telefax;
            MobilePhone = mobilePhone;
            PhoneNumber = phoneNumber;
            Email = email;
            PostAddress = postAddress;
            OfficeAddress = officeAddress;
            Initials = initials;
            Web = web;
            Categories = categories;
            ParentEnterpriseNumber = parentEnterpriseNumber;
            CustomNo1 = customNo1;
            CustomNo2 = customNo2;
            CustomNo3 = customNo3;
            Active = active;
            CreatedDate = createdDate;
            ModifiedDate = modifiedDate;
            AccessGroup = accessGroup;
            AdditionalFields = additionalFields;
            AlternativeEmail = alternativeEmail;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Recno")]
        public int? Recno { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ContactRelations")]
        public object ContactRelations { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EnterpriseNumber")]
        public string EnterpriseNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ExternalID")]
        public string ExternalID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Telefax")]
        public string Telefax { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MobilePhone")]
        public string MobilePhone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PhoneNumber")]
        public string PhoneNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PostAddress")]
        public GetEnterprisesOKResponseEnterprisesItemPostAddress PostAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OfficeAddress")]
        public GetEnterprisesOKResponseEnterprisesItemOfficeAddress OfficeAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Initials")]
        public string Initials { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Web")]
        public string Web { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Categories")]
        public IList<string> Categories { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ParentEnterpriseNumber")]
        public string ParentEnterpriseNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomNo1")]
        public string CustomNo1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomNo2")]
        public string CustomNo2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomNo3")]
        public string CustomNo3 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Active")]
        public bool? Active { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CreatedDate")]
        public DateTime? CreatedDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ModifiedDate")]
        public DateTime? ModifiedDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccessGroup")]
        public string AccessGroup { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AdditionalFields")]
        public object AdditionalFields { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AlternativeEmail")]
        public string AlternativeEmail { get; set; }

    }
}
