// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class GetEnterprisesArgs
    {
        /// <summary>
        /// Initializes a new instance of the GetEnterprisesArgs class.
        /// </summary>
        public GetEnterprisesArgs() { }

        /// <summary>
        /// Initializes a new instance of the GetEnterprisesArgs class.
        /// </summary>
        public GetEnterprisesArgs(GetEnterprisesArgsParameter parameter = default(GetEnterprisesArgsParameter))
        {
            Parameter = parameter;
        }

        /// <summary>
        /// GetEnterprisesParameter.
        /// </summary>
        [JsonProperty(PropertyName = "parameter")]
        public GetEnterprisesArgsParameter Parameter { get; set; }

    }
}
