// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class GetEnterprisesArgsParameterCreatedDateRange
    {
        /// <summary>
        /// Initializes a new instance of the
        /// GetEnterprisesArgsParameterCreatedDateRange class.
        /// </summary>
        public GetEnterprisesArgsParameterCreatedDateRange() { }

        /// <summary>
        /// Initializes a new instance of the
        /// GetEnterprisesArgsParameterCreatedDateRange class.
        /// </summary>
        public GetEnterprisesArgsParameterCreatedDateRange(DateTime? fromProperty = default(DateTime?), DateTime? to = default(DateTime?))
        {
            FromProperty = fromProperty;
            To = to;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "From")]
        public DateTime? FromProperty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "To")]
        public DateTime? To { get; set; }

    }
}
