// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// GetPrivatePersonsParameter.
    /// </summary>
    public partial class GetPrivatePersonsArgsParameter
    {
        /// <summary>
        /// Initializes a new instance of the GetPrivatePersonsArgsParameter
        /// class.
        /// </summary>
        public GetPrivatePersonsArgsParameter() { }

        /// <summary>
        /// Initializes a new instance of the GetPrivatePersonsArgsParameter
        /// class.
        /// </summary>
        public GetPrivatePersonsArgsParameter(string aDContextUser = default(string), int? recno = default(int?), string name = default(string), string externalID = default(string), string personalIdNumber = default(string), GetPrivatePersonsArgsParameterCreatedDateRange createdDateRange = default(GetPrivatePersonsArgsParameterCreatedDateRange), GetPrivatePersonsArgsParameterModifiedDateRange modifiedDateRange = default(GetPrivatePersonsArgsParameterModifiedDateRange), int? page = default(int?), int? maxRows = default(int?), string sortCriterion = default(string), bool? active = default(bool?), IList<string> categories = default(IList<string>), string customNo1 = default(string), string customNo2 = default(string), string customNo3 = default(string), IList<GetPrivatePersonsArgsParameterAdditionalFieldsItem> additionalFields = default(IList<GetPrivatePersonsArgsParameterAdditionalFieldsItem>), bool? includeCustomFields = default(bool?), IList<GetPrivatePersonsArgsParameterDateCriteriaItem> dateCriteria = default(IList<GetPrivatePersonsArgsParameterDateCriteriaItem>), string email = default(string), string alternativeEmail = default(string), IList<GetPrivatePersonsArgsParameterAdditionalListFieldsItem> additionalListFields = default(IList<GetPrivatePersonsArgsParameterAdditionalListFieldsItem>))
        {
            ADContextUser = aDContextUser;
            Recno = recno;
            Name = name;
            ExternalID = externalID;
            PersonalIdNumber = personalIdNumber;
            CreatedDateRange = createdDateRange;
            ModifiedDateRange = modifiedDateRange;
            Page = page;
            MaxRows = maxRows;
            SortCriterion = sortCriterion;
            Active = active;
            Categories = categories;
            CustomNo1 = customNo1;
            CustomNo2 = customNo2;
            CustomNo3 = customNo3;
            AdditionalFields = additionalFields;
            IncludeCustomFields = includeCustomFields;
            DateCriteria = dateCriteria;
            Email = email;
            AlternativeEmail = alternativeEmail;
            AdditionalListFields = additionalListFields;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ADContextUser")]
        public string ADContextUser { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Recno")]
        public int? Recno { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ExternalID")]
        public string ExternalID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PersonalIdNumber")]
        public string PersonalIdNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CreatedDateRange")]
        public GetPrivatePersonsArgsParameterCreatedDateRange CreatedDateRange { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ModifiedDateRange")]
        public GetPrivatePersonsArgsParameterModifiedDateRange ModifiedDateRange { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Page")]
        public int? Page { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MaxRows")]
        public int? MaxRows { get; set; }

        /// <summary>
        /// Possible values include: 'RecnoDescending', 'RecnoAscending'
        /// </summary>
        [JsonProperty(PropertyName = "SortCriterion")]
        public string SortCriterion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Active")]
        public bool? Active { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Categories")]
        public IList<string> Categories { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomNo1")]
        public string CustomNo1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomNo2")]
        public string CustomNo2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomNo3")]
        public string CustomNo3 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AdditionalFields")]
        public IList<GetPrivatePersonsArgsParameterAdditionalFieldsItem> AdditionalFields { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IncludeCustomFields")]
        public bool? IncludeCustomFields { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateCriteria")]
        public IList<GetPrivatePersonsArgsParameterDateCriteriaItem> DateCriteria { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AlternativeEmail")]
        public string AlternativeEmail { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AdditionalListFields")]
        public IList<GetPrivatePersonsArgsParameterAdditionalListFieldsItem> AdditionalListFields { get; set; }

    }
}
