// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class SynchronizeEnterpriseArgsParameterContactRelationsItem
    {
        /// <summary>
        /// Initializes a new instance of the
        /// SynchronizeEnterpriseArgsParameterContactRelationsItem class.
        /// </summary>
        public SynchronizeEnterpriseArgsParameterContactRelationsItem() { }

        /// <summary>
        /// Initializes a new instance of the
        /// SynchronizeEnterpriseArgsParameterContactRelationsItem class.
        /// </summary>
        public SynchronizeEnterpriseArgsParameterContactRelationsItem(int? recno = default(int?), string referenceNumber = default(string), string externalId = default(string), string role = default(string))
        {
            Recno = recno;
            ReferenceNumber = referenceNumber;
            ExternalId = externalId;
            Role = role;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Recno")]
        public int? Recno { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ReferenceNumber")]
        public string ReferenceNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ExternalId")]
        public string ExternalId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Role")]
        public string Role { get; set; }

    }
}
