// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class UpdateContactPersonArgs
    {
        /// <summary>
        /// Initializes a new instance of the UpdateContactPersonArgs class.
        /// </summary>
        public UpdateContactPersonArgs() { }

        /// <summary>
        /// Initializes a new instance of the UpdateContactPersonArgs class.
        /// </summary>
        public UpdateContactPersonArgs(UpdateContactPersonArgsParameter parameter = default(UpdateContactPersonArgsParameter))
        {
            Parameter = parameter;
        }

        /// <summary>
        /// UpdateContactPersonParameter.
        /// </summary>
        [JsonProperty(PropertyName = "parameter")]
        public UpdateContactPersonArgsParameter Parameter { get; set; }

    }
}
