// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SI.Shared.Sif.Testclient.Common.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class UpdatePrivatePersonArgs
    {
        /// <summary>
        /// Initializes a new instance of the UpdatePrivatePersonArgs class.
        /// </summary>
        public UpdatePrivatePersonArgs() { }

        /// <summary>
        /// Initializes a new instance of the UpdatePrivatePersonArgs class.
        /// </summary>
        public UpdatePrivatePersonArgs(UpdatePrivatePersonArgsParameter parameter = default(UpdatePrivatePersonArgsParameter))
        {
            Parameter = parameter;
        }

        /// <summary>
        /// UpdatePrivatePersonParameter.
        /// </summary>
        [JsonProperty(PropertyName = "parameter")]
        public UpdatePrivatePersonArgsParameter Parameter { get; set; }

    }
}
